### ISSUE TITLE
Differences with js-stringify?

### ISSUE THREAD

**Issue by stevenvachon** [blakeembrey/javascript-stringify#15]
[js-stringify](https://npmjs.com/js-stringify)

**Comment by blakeembrey** [comment]
Please take some time to do reviews for yourself instead of putting the burden on an OSS maintainer to run comparisons for you. That said, if you look at https://github.com/pugjs/js-stringify/blob/master/index.js all it is is a slightly modified JSON stringify. Compared to the goal of this module which is to stringify the entire JavaScript object representation so it can be evaluated at a later date.

**Comment by stevenvachon** [comment]
Can js-stringify not be evaluated at a later date? The purpose for a readme is to describe why the package is useful, not just how it's used.

**Comment by blakeembrey** [comment]
What didn’t you understand from the README? If you don’t feel it’s good enough, submit a PR. I looked at the code for the library you asked me to compare because it’s README had no examples of what it did so I couldn’t compare it.
